# Generated by Django 2.2 on 2019-04-12 18:21
from django.db import migrations

##
# Por um descuido havia criado o nome do campo com caracteresespeciais
# Essa migrations é só para corrigir o nome do campo que armazena a data da atualizacao do registro
##

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Follower', 'data_atualizaçãp', 'data_atualizacao')
    ]
